In [1]:
#Sort, Search & Counting Funcions

In [3]:
import numpy as np

In [9]:
arr = np.array([4, 3, 4, 5, 6, 72, 3, 3, 455, 5, 6, 6])

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [13]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [15]:
np.searchsorted(arr, 34)

12

In [17]:
arr1 = np.array([0, 345, 454, 0, 0, 0, 0, 0])

In [19]:
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [21]:
np.count_nonzero(arr1)

2

In [23]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
np.where(arr > 6)

(array([5, 8]),)

In [29]:
np.extract(arr > 3, arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])