In [3]:
#Numpy - Array Manipulation

In [5]:
import numpy as np

In [7]:
arr = np.random.randint(1,10, (3,4))

In [9]:
arr

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [11]:
arr.reshape(6,2)

array([[6, 7],
       [7, 4],
       [5, 8],
       [7, 7],
       [8, 2],
       [2, 9]])

In [13]:
arr.reshape(2,6)

array([[6, 7, 7, 4, 5, 8],
       [7, 7, 8, 2, 2, 9]])

In [15]:
arr

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [17]:
arr.T

array([[6, 5, 8],
       [7, 8, 2],
       [7, 7, 2],
       [4, 7, 9]])

In [19]:
arr.flatten()

array([6, 7, 7, 4, 5, 8, 7, 7, 8, 2, 2, 9])

In [21]:
arr1 = np.array([1,2,3,3,4])

In [23]:
arr1.ndim

1

In [25]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [27]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [29]:
arr

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [31]:
np.squeeze(arr)

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [33]:
data = np.array([[1], [2], [3]])

In [35]:
data

array([[1],
       [2],
       [3]])

In [37]:
np.squeeze(data)

array([1, 2, 3])

In [39]:
arr1

array([1, 2, 3, 3, 4])

In [41]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [43]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [45]:
arr1

array([1, 2, 3, 3, 4])

In [47]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [49]:
#Numpy - Binary Operators

In [51]:
arr1 = np.random.randint(1,10, (3,4))

In [55]:
arr2 = np.random.randint(1,10, (3,4))

In [57]:
arr1

array([[3, 8, 5, 4],
       [5, 1, 3, 1],
       [7, 6, 4, 1]])

In [59]:
arr2

array([[3, 8, 3, 8],
       [3, 7, 7, 8],
       [7, 4, 7, 3]])

In [61]:
arr1 + arr2

array([[ 6, 16,  8, 12],
       [ 8,  8, 10,  9],
       [14, 10, 11,  4]])

In [63]:
arr1 * arr2

array([[ 9, 64, 15, 32],
       [15,  7, 21,  8],
       [49, 24, 28,  3]])

In [67]:
arr1 / arr2

array([[1.        , 1.        , 1.66666667, 0.5       ],
       [1.66666667, 0.14285714, 0.42857143, 0.125     ],
       [1.        , 1.5       , 0.57142857, 0.33333333]])

In [69]:
arr1 - arr2

array([[ 0,  0,  2, -4],
       [ 2, -6, -4, -7],
       [ 0,  2, -3, -2]])

In [71]:
arr1 % arr2

array([[0, 0, 2, 4],
       [2, 1, 3, 1],
       [0, 2, 4, 1]])

In [73]:
arr1 ** arr2

array([[      27, 16777216,      125,    65536],
       [     125,        1,     2187,        1],
       [  823543,     1296,    16384,        1]])

In [75]:
arr1 & arr2

array([[3, 8, 1, 0],
       [1, 1, 3, 0],
       [7, 4, 4, 1]])

In [77]:
~arr1

array([[-4, -9, -6, -5],
       [-6, -2, -4, -2],
       [-8, -7, -5, -2]])

In [79]:
arr1 | arr2

array([[ 3,  8,  7, 12],
       [ 7,  7,  7,  9],
       [ 7,  6,  7,  3]])

In [81]:
arr1 > arr2

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [83]:
#Numpy - String Functions

In [87]:
arr = np.array(["Pranav", "Avasthi"])

In [89]:
arr

array(['Pranav', 'Avasthi'], dtype='<U7')

In [91]:
np.char.upper(arr)

array(['PRANAV', 'AVASTHI'], dtype='<U7')

In [93]:
np.char.title(arr)

array(['Pranav', 'Avasthi'], dtype='<U7')

In [95]:
np.char.capitalize(arr)

array(['Pranav', 'Avasthi'], dtype='<U7')