In [3]:
#Numpy - Array Manipulation

In [5]:
import numpy as np

In [7]:
arr = np.random.randint(1,10, (3,4))

In [9]:
arr

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [11]:
arr.reshape(6,2)

array([[6, 7],
       [7, 4],
       [5, 8],
       [7, 7],
       [8, 2],
       [2, 9]])

In [13]:
arr.reshape(2,6)

array([[6, 7, 7, 4, 5, 8],
       [7, 7, 8, 2, 2, 9]])

In [15]:
arr

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [17]:
arr.T

array([[6, 5, 8],
       [7, 8, 2],
       [7, 7, 2],
       [4, 7, 9]])

In [19]:
arr.flatten()

array([6, 7, 7, 4, 5, 8, 7, 7, 8, 2, 2, 9])

In [21]:
arr1 = np.array([1,2,3,3,4])

In [23]:
arr1.ndim

1

In [25]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [27]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [29]:
arr

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [31]:
np.squeeze(arr)

array([[6, 7, 7, 4],
       [5, 8, 7, 7],
       [8, 2, 2, 9]])

In [33]:
data = np.array([[1], [2], [3]])

In [35]:
data

array([[1],
       [2],
       [3]])

In [37]:
np.squeeze(data)

array([1, 2, 3])

In [39]:
arr1

array([1, 2, 3, 3, 4])

In [41]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [43]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [45]:
arr1

array([1, 2, 3, 3, 4])

In [47]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])