In [2]:
import numpy as np

In [6]:
l = [1,2,3,4]

In [10]:
arr = np.array(l)

In [12]:
type(arr)

numpy.ndarray

In [14]:
# N- dimensional Array

In [18]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
np.asarray([1, 2, 3, 4])

array([1, 2, 3, 4])

In [22]:
a = [2, 3, 4]

In [24]:
np.asanyarray(a)

array([2, 3, 4])

In [26]:
b = np.matrix(l)

In [28]:
b

matrix([[1, 2, 3, 4]])

In [30]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [32]:
a = np.array(l)

In [34]:
a

array([1, 2, 3, 4])

In [36]:
c = a

In [38]:
c

array([1, 2, 3, 4])

In [40]:
c[0]

1

In [42]:
c[0] = 100

In [44]:
c

array([100,   2,   3,   4])

In [46]:
a

array([100,   2,   3,   4])

In [48]:
d = np.copy(a)

In [50]:
d

array([100,   2,   3,   4])

In [52]:
a

array([100,   2,   3,   4])

In [54]:
a[1] = 400

In [56]:
a

array([100, 400,   3,   4])

In [58]:
d

array([100,   2,   3,   4])

In [60]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
iterable = (i*i for i in range(5))

In [66]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [68]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [70]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [72]:
#Numpy - Data Types

In [74]:
l = [2, 3, 4, 5, 6]

In [76]:
arr = np.array(l)

In [78]:
arr

array([2, 3, 4, 5, 6])

In [80]:
arr.ndim

1

In [86]:
arr2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])

In [88]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [90]:
arr2.ndim

2

In [92]:
arr2.size

8

In [94]:
arr.size

5

In [98]:
arr.shape

(5,)

In [100]:
arr2.shape

(2, 4)

In [102]:
arr.dtype

dtype('int64')

In [104]:
arr2.dtype

dtype('int64')

In [106]:
arr3 = np.array([(1.4, 45, 45), (23, 45, 66)])

In [108]:
arr3

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [110]:
arr3.dtype

dtype('float64')

In [114]:
list(range(5))

[0, 1, 2, 3, 4]

In [118]:
# it will not work -> list(range(0.1, 5))

In [120]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [126]:
list(np.arange(2.3, 5.6, 0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [128]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [130]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [136]:
np.zeros((3, 4)) #x,y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
np.zeros((3, 4, 2)) #z,x,y

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [142]:
 arr4 = np.zeros((3, 4, 2, 3))

In [144]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [146]:
arr4.ndim

4

In [148]:
np.ones(4)

array([1., 1., 1., 1.])

In [154]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [158]:
on = np.ones((2, 3, 2))

In [160]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [162]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [166]:
np.empty((3, 6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [168]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [174]:
np.logspace(2, 5, 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])