In [2]:
import numpy as np

In [6]:
l = [1,2,3,4]

In [10]:
arr = np.array(l)

In [12]:
type(arr)

numpy.ndarray

In [14]:
# N- dimensional Array

In [18]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
np.asarray([1, 2, 3, 4])

array([1, 2, 3, 4])

In [22]:
a = [2, 3, 4]

In [24]:
np.asanyarray(a)

array([2, 3, 4])

In [26]:
b = np.matrix(l)

In [28]:
b

matrix([[1, 2, 3, 4]])

In [30]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [32]:
a = np.array(l)

In [34]:
a

array([1, 2, 3, 4])

In [36]:
c = a

In [38]:
c

array([1, 2, 3, 4])

In [40]:
c[0]

1

In [42]:
c[0] = 100

In [44]:
c

array([100,   2,   3,   4])

In [46]:
a

array([100,   2,   3,   4])

In [48]:
d = np.copy(a)

In [50]:
d

array([100,   2,   3,   4])

In [52]:
a

array([100,   2,   3,   4])

In [54]:
a[1] = 400

In [56]:
a

array([100, 400,   3,   4])

In [58]:
d

array([100,   2,   3,   4])

In [60]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
iterable = (i*i for i in range(5))

In [66]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [68]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [70]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [72]:
#Numpy - Data Types

In [74]:
l = [2, 3, 4, 5, 6]

In [76]:
arr = np.array(l)

In [78]:
arr

array([2, 3, 4, 5, 6])

In [80]:
arr.ndim

1

In [86]:
arr2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])

In [88]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [90]:
arr2.ndim

2

In [92]:
arr2.size

8

In [94]:
arr.size

5

In [98]:
arr.shape

(5,)

In [100]:
arr2.shape

(2, 4)

In [102]:
arr.dtype

dtype('int64')

In [104]:
arr2.dtype

dtype('int64')

In [106]:
arr3 = np.array([(1.4, 45, 45), (23, 45, 66)])

In [108]:
arr3

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [110]:
arr3.dtype

dtype('float64')

In [114]:
list(range(5))

[0, 1, 2, 3, 4]

In [118]:
# it will not work -> list(range(0.1, 5))

In [120]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [126]:
list(np.arange(2.3, 5.6, 0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [128]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [130]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [136]:
np.zeros((3, 4)) #x,y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
np.zeros((3, 4, 2)) #z,x,y

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [142]:
 arr4 = np.zeros((3, 4, 2, 3))

In [144]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [146]:
arr4.ndim

4

In [148]:
np.ones(4)

array([1., 1., 1., 1.])

In [154]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [158]:
on = np.ones((2, 3, 2))

In [160]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [162]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [166]:
np.empty((3, 6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [168]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [174]:
np.logspace(2, 5, 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [186]:
arr = np.random.randn(3,4) # Data generated where mean = 0 & standard deviation = 1

In [180]:
import pandas as pd

In [182]:
pd.DataFrame(arr)

0         1         2         3
0  0.183935  0.622967 -0.270189 -0.573853
1  0.132140  0.671727  0.220979  1.516122
2  1.354545 -0.492876 -0.683089 -2.687180

In [184]:
np.random.rand(3,4)

array([[0.04176561, 0.83983012, 0.32246329, 0.64970091],
       [0.64438064, 0.0070004 , 0.391547  , 0.02464134],
       [0.37865474, 0.25093398, 0.97130272, 0.97776426]])

In [194]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [196]:
arr = np.random.rand(3,4)

In [198]:
arr

array([[0.98682156, 0.20238688, 0.75865458, 0.37998112],
       [0.92461968, 0.99342425, 0.77926229, 0.06939125],
       [0.72407049, 0.30476824, 0.0960647 , 0.97556138]])

In [212]:
arr1 = arr.reshape(6,2)

In [214]:
arr1

array([[0.98682156, 0.20238688],
       [0.75865458, 0.37998112],
       [0.92461968, 0.99342425],
       [0.77926229, 0.06939125],
       [0.72407049, 0.30476824],
       [0.0960647 , 0.97556138]])

In [216]:
arr1[1][1]

0.37998112258966954

In [222]:
arr1[2:5, 1] # row, column

array([0.99342425, 0.06939125, 0.30476824])

In [226]:
arr = np.random.randint(1,100, (5,5))

In [228]:
arr

array([[51,  1,  6, 91, 35],
       [34, 32, 64, 74, 12],
       [63, 52, 14, 85, 49],
       [36, 89, 46, 62, 37],
       [16, 61, 64, 15, 76]])

In [230]:
arr > 50

array([[ True, False, False,  True, False],
       [False, False,  True,  True, False],
       [ True,  True, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True,  True, False,  True]])

In [232]:
arr[arr>50]

array([51, 91, 64, 74, 63, 52, 85, 89, 62, 61, 64, 76])

In [234]:
arr

array([[51,  1,  6, 91, 35],
       [34, 32, 64, 74, 12],
       [63, 52, 14, 85, 49],
       [36, 89, 46, 62, 37],
       [16, 61, 64, 15, 76]])

In [236]:
arr[2:4, 1:3]

array([[52, 14],
       [89, 46]])

In [238]:
arr[0][0]

51

In [240]:
arr[0][0] = 5000

In [242]:
arr

array([[5000,    1,    6,   91,   35],
       [  34,   32,   64,   74,   12],
       [  63,   52,   14,   85,   49],
       [  36,   89,   46,   62,   37],
       [  16,   61,   64,   15,   76]])

In [250]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [252]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [254]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [256]:
arr1 + arr2

array([[3, 3, 2],
       [3, 2, 2],
       [2, 2, 3]])

In [258]:
arr1 - arr2

array([[ 1, -1,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [260]:
arr1 / arr2

array([[2. , 0.5, 1. ],
       [2. , 1. , 1. ],
       [1. , 1. , 0.5]])

In [262]:
arr1 * arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [264]:
arr1 @ arr2

array([[4, 6, 5],
       [4, 6, 5],
       [3, 4, 4]])

In [266]:
arr1/0

/var/folders/rv/pw1qbgxd5xb8ks1_rywswp8m0000gn/T/ipykernel_45436/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [268]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [270]:
arr1 + 100

array([[102, 101, 101],
       [102, 101, 101],
       [101, 101, 101]])

In [272]:
arr1 ** 2

array([[4, 1, 1],
       [4, 1, 1],
       [1, 1, 1]])

In [ ]:
ar