In [1]:
#Sort, Search & Counting Funcions

In [3]:
import numpy as np

In [9]:
arr = np.array([4, 3, 4, 5, 6, 72, 3, 3, 455, 5, 6, 6])

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [13]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [15]:
np.searchsorted(arr, 34)

12

In [17]:
arr1 = np.array([0, 345, 454, 0, 0, 0, 0, 0])

In [19]:
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [21]:
np.count_nonzero(arr1)

2

In [23]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
np.where(arr > 6)

(array([5, 8]),)

In [29]:
np.extract(arr > 3, arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [31]:
#Numpy - Byte Swapping

In [33]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [35]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [37]:
#Numpy - Copies & Views

In [39]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [57]:
a = np.copy(arr) # Deep Copy

In [55]:
b = arr.view() # Shallow Copy

In [45]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [47]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [49]:
b[0] = 67

In [51]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [53]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])