In [2]:
import numpy as np

In [6]:
l = [1,2,3,4]

In [10]:
arr = np.array(l)

In [12]:
type(arr)

numpy.ndarray

In [14]:
# N- dimensional Array

In [18]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
np.asarray([1, 2, 3, 4])

array([1, 2, 3, 4])

In [22]:
a = [2, 3, 4]

In [24]:
np.asanyarray(a)

array([2, 3, 4])

In [26]:
b = np.matrix(l)

In [28]:
b

matrix([[1, 2, 3, 4]])

In [30]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [32]:
a = np.array(l)

In [34]:
a

array([1, 2, 3, 4])

In [36]:
c = a

In [38]:
c

array([1, 2, 3, 4])

In [40]:
c[0]

1

In [42]:
c[0] = 100

In [44]:
c

array([100,   2,   3,   4])

In [46]:
a

array([100,   2,   3,   4])

In [48]:
d = np.copy(a)

In [50]:
d

array([100,   2,   3,   4])

In [52]:
a

array([100,   2,   3,   4])

In [54]:
a[1] = 400

In [56]:
a

array([100, 400,   3,   4])

In [58]:
d

array([100,   2,   3,   4])

In [60]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
iterable = (i*i for i in range(5))

In [66]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [68]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [70]:
np.fromstring('4,5', sep=',')

array([4., 5.])